# (mgc, lf0, vuv, bap)
stream_sizes: [60, 1, 1, 5]
has_dynamic_features: [false, false, false, false]
num_windows: 1
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.acoustic_models.NPSSMultistreamParametricModel
  in_dim: 86
  out_dim: 67

  stream_sizes: [60, 1, 1, 5]
  reduction_factor: 2

  # NOTE: you MUST set in_lf0_idx and out_lf0_idx correctly
  # otherwise the model does't work at all
  in_rest_idx: 0
  in_lf0_idx: 51
  out_lf0_idx: 60
  # Please leave the following parameters unspecified if you want to
  # find the corresponding values automatically from in/out scalers.
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null

  # A separate model for modeling continuous log-F0
  lf0_model:
    _target_: nnsvs.acoustic_models.BiLSTMResF0NonAttentiveDecoder
    in_dim: 86
    in_ph_start_idx: 3
    in_ph_end_idx: 50
    embed_dim: 8
    out_dim: 1
    ff_hidden_dim: 4
    conv_hidden_dim: 4
    lstm_hidden_dim: 4
    num_lstm_layers: 1
    decoder_layers: 1
    decoder_hidden_dim: 4
    prenet_layers: 0
    prenet_hidden_dim: 16
    prenet_dropout: 0.5
    scaled_tanh: true
    zoneout: 0.0
    reduction_factor: 4
    downsample_by_conv: true
    in_lf0_idx: 51
    out_lf0_idx: 0
    in_lf0_min: null
    in_lf0_max: null
    out_lf0_mean: null
    out_lf0_scale: null
    use_mdn: false

  mgc_model:
    _target_: nnsvs.model.MDN
    in_dim: 87
    hidden_dim: 8
    out_dim: 60
    dim_wise: true
    num_gaussians: 4

  bap_model:
    _target_: nnsvs.model.MDN
    in_dim: 147
    hidden_dim: 8
    out_dim: 5
    dim_wise: true
    num_gaussians: 4

  vuv_model:
    _target_: nnsvs.model.FFN
    in_dim: 152
    hidden_dim: 8
    out_dim: 1

  # Spectral parameter prediction model
  mgc_model:
    _target_: nnsvs.acoustic_models.BiLSTMNonAttentiveDecoder
    in_dim: 87
    out_dim: 60
    in_ph_start_idx: 3
    in_ph_end_idx: 50
    embed_dim: 256
    ff_hidden_dim: 1024
    conv_hidden_dim: 512
    lstm_hidden_dim: 256
    num_lstm_layers: 3
    decoder_layers: 2
    decoder_hidden_dim: 1024
    prenet_layers: 2
    prenet_hidden_dim: 192
    prenet_dropout: 0.5
    zoneout: 0.0
    reduction_factor: 2
    downsample_by_conv: true

  # Aperiodic parameter prediction model
  bap_model:
    _target_: nnsvs.acoustic_models.BiLSTMNonAttentiveDecoder
    in_dim: 87
    out_dim: 3
    in_ph_start_idx: 3
    in_ph_end_idx: 50
    embed_dim: 256
    ff_hidden_dim: 1024
    conv_hidden_dim: 512
    lstm_hidden_dim: 256
    num_lstm_layers: 3
    decoder_layers: 2
    decoder_hidden_dim: 256
    prenet_layers: 2
    prenet_hidden_dim: 16
    prenet_dropout: 0.5
    zoneout: 0.0
    reduction_factor: 2
    downsample_by_conv: true

  # V/UV prediction model
  vuv_model:
    _target_: nnsvs.acoustic_models.FFConvLSTM
    in_dim: 90
    out_dim: 1
    in_ph_start_idx: 3
    in_ph_end_idx: 50
    embed_dim: 256
    ff_hidden_dim: 256
    conv_hidden_dim: 128
    lstm_hidden_dim: 64
    num_lstm_layers: 2
    bidirectional: true
    dropout: 0.1
    use_mdn: false
