defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

verbose: 100

utt_list:
in_dir:
out_dir:

# Normalize the output static features or not
normalize: false

out_scaler_path:

model:
  checkpoint:
  model_yaml:

