# (mgc, lf0, vuv, bap, vib, vib_flags)
stream_sizes: [180, 3, 1, 15, 6, 1]
has_dynamic_features: [true, true, false, true, true, false]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.model.ResSkipF0FFConvLSTM
  in_dim: 335
  out_dim: 206
  ff_hidden_dim: 512
  conv_hidden_dim: 256
  lstm_hidden_dim: 128
  dropout: 0.1
  bidirectional: truse
  # NOTE: you MUST set in_lf0_idx and out_lf0_idx correctly
  # otherwise the model does't work at all
  in_lf0_idx: 286
  out_lf0_idx: 180
  # Please leave the following parameters unspecified if you want to
  # find the corresponding values automatically from in/out scalers.
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null
