# General settings.
spk: "kiritan"
sample_rate: 48000

# exp tag(for managing experiments)
tag:

###########################################################
#                DATA PREPARATION SETTING                 #
###########################################################

# **CHANGE** this to your database path
wav_root:

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

# HTS-style question used for extracting musical/linguistic context from musicxml files
question_path: "../../_common/hed/jp_experimental.hed"

timelag_features: defaults
duration_features: defaults
acoustic_features: static_deltadelta_sinevib

# Parameter trajectory smoothing
# Ref: The NAIST Text-to-Speech System for the Blizzard Challenge 2015
trajectory_smoothing: false
trajectory_smoothing_cutoff: 50

###########################################################
#                TRAINING SETTING                         #
###########################################################

# Models
# To customize, put your config or change ones in
# conf/train/{timelag,duration,acoustic}/ and
# specify the config name below
# NOTE: *_model: model definition, *_train: general train configs,
# *_data: data configs (e.g., batch size)

timelag_model: timelag_mdn
timelag_train: myconfig
timelag_data: myconfig

duration_model: duration_mdn
duration_train: myconfig
duration_data: myconfig

acoustic_model: acoustic_resf0convlstm
acoustic_train: myconfig
acoustic_data: myconfig

# Pretrained model dir (leave empty to disable)
pretrained_expdir:

# Advanced settings for hyperparameter search with Hydra and Optuna.
# https://hydra.cc/docs/plugins/optuna_sweeper/
# NOTE: Don't use spaces for each search space configuration.
# OK: data.batch_size=range(1,16)
# NG: data.batch_size=range(1, 16)
# Example 1: data.batch_size=range(1,16) model.netG.hidden_dim=choice(32,64,128)
# Example 2: train.optim.optimizer.params.lr=interval(0.0001,0.01)
timelag_hydra_optuna_sweeper_args:
timelag_hydra_optuna_sweeper_n_trials: 100
duration_hydra_optuna_sweeper_args:
duration_hydra_optuna_sweeper_n_trials: 100
acoustic_hydra_optuna_sweeper_args:
acoustic_hydra_optuna_sweeper_n_trials: 100

# Advanced settings for hyperparameter search with Hydra and Optuna.
# https://hydra.cc/docs/plugins/optuna_sweeper/
# NOTE: Don't use spaces for each search space configuration.
# OK: data.batch_size=range(1,16)
# NG: data.batch_size=range(1, 16)
# Example 1: data.batch_size=range(1,16) model.netG.hidden_dim=choice(32,64,128)
# Example 2: train.optim.optimizer.params.lr=interval(0.0001,0.01)
timelag_hydra_optuna_sweeper_args: data.batch_size=range(1,16) model.netG.hidden_dim=choice(32,64,128,256) model.netG.num_layers=range(1,4) model.netG.num_gaussians=range(1,8) train.optim.optimizer.params.lr=interval(0.0001,0.01) train.optim.lr_scheduler.params.step_size=choice(10,20,30,40,50) train.optim.lr_scheduler.params.gamma=interval(0.1,0.9)
timelag_hydra_optuna_sweeper_n_trials: 100
duration_hydra_optuna_sweeper_args: data.batch_size=range(1,16) model.netG.hidden_dim=choice(64,128,256,512) model.netG.num_layers=range(1,4) model.netG.num_gaussians=range(1,8) train.optim.optimizer.params.lr=interval(0.0001,0.01) train.optim.lr_scheduler.params.step_size=choice(10,20,30,40,50) train.optim.lr_scheduler.params.gamma=interval(0.1,0.9)
duration_hydra_optuna_sweeper_n_trials: 100
acoustic_hydra_optuna_sweeper_args: data.batch_size=range(1,16) model.netG.dropout=choice(0.1,0.3,0.5) model.netG.lstm_hidden_dim=choice(128,256) model.netG.conv_hidden_dim=choice(128,256,512) model.netG.ff_hidden_dim=choice(256,512,1024) train.optim.optimizer.params.lr=interval(0.0001,0.01) train.optim.lr_scheduler.params.step_size=choice(10,20,30,40,50) train.optim.lr_scheduler.params.gamma=interval(0.1,0.9)
acoustic_hydra_optuna_sweeper_n_trials: 100

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################
timelag_synthesis: defaults
duration_synthesis: defaults
acoustic_synthesis: defaults

# latest.pth or best.pth
timelag_eval_checkpoint: latest.pth
duration_eval_checkpoint: latest.pth
acoustic_eval_checkpoint: latest.pth
