# (mgc, lf0, vuv, bap, vib, vib_flags)
stream_sizes: [60, 1, 1, 3, 2, 1]
has_dynamic_features: [false, false, false, false, False, False]
num_windows: 1
stream_weights:

netG:
  _target_: nnsvs.model.ResSkipF0FFConvLSTM
  in_dim: 86
  out_dim: 68
  ff_hidden_dim: 2048
  conv_hidden_dim: 1024
  lstm_hidden_dim: 256
  dropout: 0.0
  num_lstm_layers: 2
  bidirectional: true
  # Last MDN layer (disabled by default)
  use_mdn: false
  num_gaussians: 1
  dim_wise: true
  init_type: "kaiming_normal"
  # NOTE: you MUST set in_lf0_idx and out_lf0_idx correctly
  # otherwise the model does't work at all
  in_lf0_idx: 51
  out_lf0_idx: 60
  # Please leave the following parameters unspecified if you want to
  # find the corresponding values automatically from in/out scalers.
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null
