# Separate F0 model + shared encoder + (mel, vuv) decoders

# (mel, lf0, vuv)
stream_sizes: [80, 1, 1]
has_dynamic_features: [false, false, false]
num_windows: 1
stream_weights:

netG:
  _target_: nnsvs.acoustic_models.MultistreamSeparateF0MelModel
  in_dim: 86
  out_dim: 82

  stream_sizes: [80, 1, 1]
  reduction_factor: 4

  # NOTE: you MUST set in_lf0_idx and out_lf0_idx correctly
  # otherwise the model does't work at all
  in_rest_idx: 0
  in_lf0_idx: 51
  out_lf0_idx: 80
  # Please leave the following parameters unspecified if you want to
  # find the corresponding values automatically from in/out scalers.
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null

  encoder: null

  # A separate model for modeling continuous log-F0
  lf0_model:
    _target_: nnsvs.acoustic_models.BiLSTMResF0NonAttentiveDecoder
    in_dim: 86
    out_dim: 1
    ff_hidden_dim: 4
    conv_hidden_dim: 4
    lstm_hidden_dim: 4
    num_lstm_layers: 1
    decoder_layers: 1
    decoder_hidden_dim: 4
    prenet_layers: 0
    prenet_hidden_dim: 4
    prenet_dropout: 0.5
    scaled_tanh: true
    zoneout: 0.0
    reduction_factor: 4
    downsample_by_conv: true
    in_lf0_idx: 51
    out_lf0_idx: 0
    in_lf0_min: null
    in_lf0_max: null
    out_lf0_mean: null
    out_lf0_scale: null

  # Spectral parameter prediction model
  mel_model:
    _target_: nnsvs.acoustic_models.FFConvLSTM
    in_dim: 86 # (x, lf0)
    ff_hidden_dim: 4
    conv_hidden_dim: 4
    lstm_hidden_dim: 4
    num_lstm_layers: 1
    bidirectional: true
    out_dim: 80
    dropout: 0.1
    init_type: "kaiming_normal"

  # V/UV prediction model
  vuv_model:
    _target_: nnsvs.acoustic_models.FFConvLSTM
    in_dim: 86 # (x, lf0, mel)
    ff_hidden_dim: 4
    conv_hidden_dim: 4
    lstm_hidden_dim: 4
    num_lstm_layers: 1
    bidirectional: true
    out_dim: 1
    dropout: 0.1
    init_type: "kaiming_normal"

netD:
  _target_: nnsvs.discriminators.Conv2dD
  # If in_dim is not specified, it will be automatically set based on adv_streams
  in_dim: null
  channels: 2
  kernel_size: [3, 3]
  padding: [0, 0]
  padding_mode: "zeros"
  last_sigmoid: false
  init_type: "kaiming_normal"
